### PR TITLE
feat: add some optimizations

### PR DESCRIPTION
**Pull request by bgrand-ch**

### CODE REVIEW

**Comment by bgrand-ch** [comment]
@basil-wolf

Hello, I have rewritten and optimized the plugin.
I still have to update the examples and demos.

If you want to re-read the code or have any suggestions, that would be much appreciated :blush:

Have a nice day.

**Comment by darko-bw** [comment]
Hi @bgrand-ch , thanks a lot for updating the plugin. It works fine on iOS as I can test it right now. Amazing work!

**Comment by bgrand-ch** [comment]
Hello @basil-wolf 

Thanks a lot for your tests on iOS and for re-motivating me for this plugin.

Have a nice day.

**Comment by darko-bw** [comment]
It’s a pleasure @bgrand-ch You are such a great developer and your contribution to all Nativescript users with your hard work is really appreciated. Thank you so much!

**Pull request merged**
